name: Test & Report   # Название workflow

on:       # События, которые запустят workflow
  push:
    branches: [ main ]   # При пуше в ветку main
  pull_request:
    branches: [ main ]   # При создании PR в ветку main

jobs:
  test:  # Название job
    runs-on: ubuntu-latest  # ОС, на которой будет запущен job
    
    steps:
    - uses: actions/checkout@v3  # Проверка кода, клонирование репозитория
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Установка Python
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip   # Обновление pip
        pip install -r requirements.txt       # Установка зависимостей
        
    - name: Run tests
      run: |
        pytest --alluredir=allure-results  # Запуск тестов с сохранением результатов в allure-results
        
    - name: Get Allure history  # Получение истории Allure
      uses: actions/checkout@v3
      if: always()              # Выполнять даже если тесты не прошли
      continue-on-error: true   # Продолжать выполнение workflow даже если команда завершилась с ошибкой
      with:
        ref: gh-pages          # Ссылка на ветку с историей Allure
        path: gh-pages          # Путь к директории для сохранения
        
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results  # Путь к директории с результатами тестов
        allure_history: allure-history  # Путь к директории для сохранения истории Allure
        keep_reports: 20               # Количество отчетов для сохранения
        
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к GitHub
        publish_branch: gh-pages  # Ветка для публикации отчета
        publish_dir: allure-history  # Путь к директории для сохранения отчета